### ISSUE TITLE
Installing on minikube

### ISSUE THREAD

**Issue by haralambop** [kvaps/kube-opennebula#2]
While trying to deploy opennebula via helm on a minikube, I receive 

helm template . | kubectl apply -n opennebula -f -
service/opennebula-novnc unchanged
Error from server (Invalid): error when creating "STDIN": Secret "RELEASE-NAME-opennebula-one-keys" is invalid: metadata.name: Invalid value: "RELEASE-NAME-opennebula-one-keys": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

**Comment by kvaps** [comment]
Hi, this is happening due the incompatibility between Helm2 and Helm3 charts.

It seems it's a time to prepare new release!
The new branch `release-5.10` with new OpenNebula version, new features and bugfixes just been released.

Please try now. Helm3 now supported as well.
Any feedback are really welcome.

**Comment by haralambop** [comment]
/usr/local/bin/helm version
version.BuildInfo{Version:"v3.1.0", GitCommit:"b29d20baf09943e134c2fa5e1e1cab3bf93315fa", GitTreeState:"clean", GoVersion:"go1.13.7"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0-k3s.1", GitCommit:"dacbba10ba597c72898e0ee747f9a855ab093bc9", GitTreeState:"clean", BuildDate:"2019-12-11T20:03:48Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}


helm install opennebula helm/opennebula -f values.yaml --set oned.createCluster=1 --wait
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"

**Comment by kvaps** [comment]
> Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"

You have no prometheus installed, try `--set exporter.enabled=false`

**Comment by haralambop** [comment]
alpine-bare:~/kube-opennebula$ helm install opennebula helm/opennebula -f values.yaml --set oned.createCluster=1 --wait --set exporter.enabled=false
Error: timed out waiting for the condition

**Comment by kvaps** [comment]
Is there any logs? Have you checked your pods?

**Comment by haralambop** [comment]
kubectl get pods
NAME                                              READY   STATUS             RESTARTS   AGE
opennebula-opennebula-exporter-7f65f4f88d-gxwtq   0/1     ImagePullBackOff   0          5h42m
opennebula-opennebula-flow-6f88bc595-ljzmn        1/1     Running            0          5h42m
opennebula-opennebula-gate-67975df794-kbrkn       1/1     Running            0          5h42m
opennebula-opennebula-hem-65d799c556-kwp5j        1/1     Running            0          5h42m
opennebula-opennebula-memcached-5c964876f-fx548   1/1     Running            0          5h42m
opennebula-opennebula-novnc-7c5c7968b9-qpprm      1/1     Running            0          5h42m
opennebula-opennebula-oned-0                      0/2     CrashLoopBackOff   71         5h42m
opennebula-opennebula-oned-1                      0/2     CrashLoopBackOff   71         5h42m
opennebula-opennebula-oned-2                      0/2     CrashLoopBackOff   71         5h42m
opennebula-opennebula-sched-76b554774-wwhg5       1/1     Running            0          5h42m
opennebula-opennebula-sunstone-569785cbf6-89zfb   1/1     Running            0          5h42m
opennebula-opennebula-sunstone-569785cbf6-d9dds   1/1     Running            0          5h42m
opennebula-opennebula-sunstone-569785cbf6-xk5hf   1/1     Running            0          5h42m

kubectl logs opennebula-opennebula-oned-0
error: a container name must be specified for pod opennebula-opennebula-oned-0, choose one of: [mysql oned]

kubectl logs opennebula-opennebula-oned-1
error: a container name must be specified for pod opennebula-opennebula-oned-1, choose one of: [mysql oned]

kubectl logs opennebula-opennebula-oned-2
error: a container name must be specified for pod opennebula-opennebula-oned-2, choose one of: [mysql oned]

kubectl logs opennebula-opennebula-exporter-7f65f4f88d-gxwtq
Error from server (BadRequest): container "exporter" in pod "opennebula-opennebula-exporter-7f65f4f88d-gxwtq" is waiting to start: trying and failing to pull image

**Comment by kvaps** [comment]
try specify oned container
```
kubectl logs opennebula-opennebula-oned-0 oned
```

**Comment by kvaps** [comment]
Hi, there were definitely some problems with the initial bootstrap procedure.
Fix released in 89d602d , so now it should working fine.

Please checkout and try deploy again. Thanks for the report!
