### ISSUE TITLE
login credentials

### ISSUE THREAD

**Issue by younus2019** [kvaps/kube-opennebula#4]
I have deployed the opennebula in cluster. now i can able to view opennebula login screen. i don't have login credential for opennebula. how to get login credentails to logon opennebula?

**Comment by kvaps** [comment]
Hi, if you didn't set them manually, then they were generated automatically.
You can get passwords from opennebula-one-keys secret.

https://github.com/kvaps/kube-opennebula/blob/c8f5991a22404b0601f81b925eea4db639538bab/helm/opennebula/templates/oned-secret.yaml#L18-L22

**Comment by younus2019** [comment]
Thank you kvaps.
