### ISSUE TITLE
Issues with shared volume.

### ISSUE THREAD

**Issue by aredan** [kvaps/kube-opennebula#7]
I installed the Helm Chart first without the shared volume, it worked great, later I enable the shared volume in the values.yaml and before running the update I installed the NFS server indicated in https://github.com/kvaps/kube-opennebula/tree/master/examples/prod/deploy/nfs-server-provisioner  the helm upgrade fails.

 Just to be sure, I delete the entire deployment, even the namespace, and started from scratch this time with share volume enable.
 
![image](https://user-images.githubusercontent.com/939894/129582730-10590aa2-81f9-475c-955a-e9e220ee25c4.png)

![image](https://user-images.githubusercontent.com/939894/129582875-d9da3202-1bc1-469b-9f06-086074fc4e3f.png)

**Comment by kvaps** [comment]
Hi, what setup do you have: Kubernetes environment and CNI plugin? Is nfs-server-provisioner pod is running?

**Comment by aredan** [comment]
Hello.
I have a 5 node k3s cluster with flannel as CNI. Yes, the NFS-server-provisioner was running, I deleted everything to check the values files and do another test but first wanted to write an issue to look for help.
One more thing, I have longhorn as storage and it has RWX support, I tried using that instead of the NFS and it displays the same error.

**Comment by kvaps** [comment]
Interesting, looks like your node does not support nfs mounts, try repeating this command manually on the node:

```
mount -t nfs -o vers=3 10.43.250.158:/export/pvc-752af35d-8aeb-4831-bf7c-fd7ec9f02934 /mnt
```

**Comment by aredan** [comment]
Sorry for the delay in responding to your request.
I find out that no only this deployment was failing to share a volume, in the end, I was messing the nfs-commong package on my working nodes so there was no tool available to use the shared NFS.
It is working now. Thanks!
